import { Region, PuebloMagico, PuebloComparativo } from './types';

const regionesData: Region[] = [
  {
    id: 1,
    nombre: 'Huasteca',
    descripcion: 'Region tropical al oriente del estado, caracterizada por selvas, rios caudalosos, cascadas monumentales y una rica herencia cultural Tenek.',
    colorHex: '#166534',
    parajes: [
      {
        id: 1,
        nombre: 'Cascada de Tamul',
        slug: 'cascada-de-tamul',
        descripcion: 'Caida de agua de 105 metros de altura formada en la convergencia del rio Santa Maria y el rio Gallinas, que precipita sobre el rio Tampaon.',
        tokenIcon: 'Waves',
        municipio: 'Aquismon',
        clima: 'Semicalido humedo',
        logistica: 'Acceso en pangas desde La Morena o Tanchachin, navegando contra corriente e incluyendo una parada en el cenote lateral Cueva del Agua. Temporada ideal: noviembre a mayo.',
        svgX: 450,
        svgY: 330,
      },
      {
        id: 2,
        nombre: 'Jardin Escultorico "Las Pozas"',
        slug: 'jardin-escultorico-las-pozas',
        descripcion: 'Laberinto surrealista inmerso en la selva humeda con 36 estructuras de concreto creadas por Edward James.',
        tokenIcon: 'Palmtree',
        municipio: 'Xilitla',
        clima: 'Selva humeda de montana',
        logistica: 'Las corrientes hidricas atraviesan la propiedad formando cascadas menores y pozas naturales de inmersion aptas para nadar.',
        svgX: 515,
        svgY: 410,
      },
      {
        id: 3,
        nombre: 'Sotano de las Golondrinas',
        slug: 'sotano-de-las-golondrinas',
        descripcion: 'Colosal abismo vertical de 512 metros de profundidad absoluta y 60 metros de diametro en su apertura.',
        tokenIcon: 'Compass',
        municipio: 'Aquismon',
        clima: 'Templado humedo',
        logistica: 'Alberga una poblacion masiva de vencejos de pecho blanco y cotorras de cueva que emergen en espiral por la manana.',
        svgX: 470,
        svgY: 370,
      },
      {
        id: 4,
        nombre: 'Sotano de las Huahuas',
        slug: 'sotano-de-las-huahuas',
        descripcion: 'Santuario geologico de 478 metros de profundidad que sirve de refugio para los pericos verdes locales (huahuas).',
        tokenIcon: 'Mountain',
        municipio: 'Aquismon',
        clima: 'Templado humedo',
        logistica: 'Es un paraiso para observadores de aves. Se requiere caminata de montana para acceder al borde del abismo.',
        svgX: 490,
        svgY: 440,
      },
      {
        id: 5,
        nombre: 'Nacimiento de Tambaque',
        slug: 'nacimiento-de-tambaque',
        descripcion: 'Balneario natural y apacible donde el agua brota directamente desde la base de rocas calizas, creando pozas cristalinas de baja profundidad.',
        tokenIcon: 'Droplets',
        municipio: 'Aquismon',
        clima: 'Calido humedo',
        logistica: 'Ideales para el turismo familiar. Cuenta con senderos adoquinados y palapas rusticas.',
        svgX: 490,
        svgY: 320,
      },
      {
        id: 6,
        nombre: 'Cascada El Meco',
        slug: 'cascada-el-meco',
        descripcion: 'Caidas de agua escalonadas con mirador panoramico inmersas en la espesura de la selva.',
        tokenIcon: 'TrendingDown',
        municipio: 'Xilitla (Periferia)',
        clima: 'Calido humedo',
        logistica: 'Ofrece una experiencia acuatica familiar mas accesible y segura que el rio Tampaon.',
        svgX: 530,
        svgY: 370,
      },
    ],
    pueblos: [
      {
        id: 1,
        nombre: 'Aquismon',
        slug: 'aquismon',
        descripcionBreve: 'Epicentro del ecoturismo extremo en la Huasteca Potosina, hogar de la cascada mas alta de Mexico accesible por rio y de abismos verticales de clase mundial.',
        imagenUrl: '/images/aquismon.jpg',
        altitud: 100,
      },
      {
        id: 2,
        nombre: 'Xilitla',
        slug: 'xilitla',
        descripcionBreve: 'Enclave surrealista en la selva huasteca, donde las esculturas de concreto de Edward James emergen entre la neblina tropical.',
        imagenUrl: '/images/xilitla.jpg',
        altitud: 600,
      },
    ],
  },
  {
    id: 2,
    nombre: 'Altiplano',
    descripcion: 'Vasta meseta semidesertica al norte del estado, con paisajes de alta montana y legado minero colonial.',
    colorHex: '#B45309',
    parajes: [
      {
        id: 7,
        nombre: 'Desierto Sagrado de Wirikuta',
        slug: 'desierto-sagrado-wirikuta',
        descripcion: 'Area Natural Protegida estatal de mas de 140,000 hectareas que incluye el Cerro del Quemado.',
        tokenIcon: 'Sun',
        municipio: 'Real de Catorce (Periferia)',
        clima: 'Seco desertico',
        logistica: 'Es el territorio sagrado y punto fundacional del universo para la nacion Wixarika (huichol), utilizado para peregrinaciones misticas y la recoleccion ritual del cactus endemico peyote (hikuri).',
        svgX: 170,
        svgY: 110,
      },
    ],
    pueblos: [
      {
        id: 3,
        nombre: 'Real de Catorce',
        slug: 'real-de-catorce',
        descripcionBreve: 'Pueblo fantasma minero suspendido a 2,700 metros de altitud en el semidesierto potosino, accesible unicamente a traves de un tunel de piedra del siglo XIX.',
        imagenUrl: '/images/real-de-catorce.jpg',
        altitud: 2700,
      },
    ],
  },
  {
    id: 3,
    nombre: 'Centro',
    descripcion: 'Corazon geografico y cultural del estado, con tradiciones textiles ancestrales, haciendas historicas y balnearios.',
    colorHex: '#9A3412',
    parajes: [
      {
        id: 8,
        nombre: 'Aguas Termales de Lourdes',
        slug: 'aguas-termales-lourdes',
        descripcion: 'Manantial freatico de agua termal descubierto hacia 1890 con fuerte composicion sulfurosa y propiedades curativas.',
        tokenIcon: 'Activity',
        municipio: 'Santa Maria del Rio',
        clima: 'Templado',
        logistica: 'Sus aguas son de tonalidad azul verdosa. Se ubica en los terrenos de la Ex Hacienda La Labor del Rio, operando como un cluster de turismo de bienestar.',
        svgX: 170,
        svgY: 360,
      },
      {
        id: 9,
        nombre: 'Cascada El Salto / Senor del Amparo',
        slug: 'cascada-el-salto',
        descripcion: 'Rareza geomorfologica de entre 30 y 40 metros de altura que desciende por roca viva en un entorno de cerros aridos y cactaceas.',
        tokenIcon: 'CloudRain',
        municipio: 'Santa Maria del Rio',
        clima: 'Semiarido',
        logistica: 'Su comportamiento es estrictamente estacional: tiene un caudal espectacular de julio a octubre y permanece completamente seca durante el estiaje primaveral.',
        svgX: 180,
        svgY: 320,
      },
      {
        id: 10,
        nombre: 'Presa La Muneca',
        slug: 'presa-la-muneca',
        descripcion: 'Inmenso embalse artificial alimentado por el Rio Jofre, utilizado para la pesca deportiva de lobina negra, carpa y mojarra.',
        tokenIcon: 'Anchor',
        municipio: 'Tierra Nueva',
        clima: 'Templado humedo',
        logistica: 'Bajo su superficie yacen las ruinas sumergidas de la antigua comunidad de Vigas; durante el estiaje es posible ver emerger la cupula de la capilla del Senor de la Piedad.',
        svgX: 230,
        svgY: 380,
      },
    ],
    pueblos: [
      {
        id: 4,
        nombre: 'Santa Maria del Rio',
        slug: 'santa-maria-del-rio',
        descripcionBreve: 'Capital mundial del rebozo mexicano, donde la tradicion textil de cuatro siglos se preserva en telares de cintura.',
        imagenUrl: '/images/santa-maria-del-rio.jpg',
        altitud: 1700,
      },
      {
        id: 5,
        nombre: 'Tierra Nueva',
        slug: 'tierra-nueva',
        descripcionBreve: 'Pueblo serrano de canadas profundas y laja roja, donde una iglesia sumergida emerge cuando desciende el nivel de la presa.',
        imagenUrl: '/images/tierra-nueva.jpg',
        altitud: 1800,
      },
    ],
  },
  {
    id: 4,
    nombre: 'Media',
    descripcion: 'Zona de transicion entre la sierra y las planicies aridas, con legado de frontera civilizatoria.',
    colorHex: '#A16207',
    parajes: [
      {
        id: 11,
        nombre: 'Laguna de la Media Luna',
        slug: 'laguna-media-luna',
        descripcion: 'Extenso manantial y laguna natural de aguas termales sumamente cristalinas con tonalidades azul zafiro.',
        tokenIcon: 'Eye',
        municipio: 'Rioverde',
        clima: 'Calido semihumedo',
        logistica: 'Mantiene una temperatura constante idonea durante todo el ano para la practica de buceo autonomo, natacion, snorkel y exploracion subacuatica, rodeada de un entorno natural arbolado.',
        svgX: 340,
        svgY: 410,
      },
      {
        id: 12,
        nombre: 'Manantiales Los Peroles',
        slug: 'manantiales-los-peroles',
        descripcion: 'Oasis agreste y virgen desprovisto de infraestructura comercial o senal celular. Ofrece pozas de aguas termales cristalinas.',
        tokenIcon: 'TreePine',
        municipio: 'Ciudad del Maiz',
        clima: 'Templado',
        logistica: 'Rodeadas por un bosque de cipreses calvos o sabinos ancestrales. Alberga al sabino "Maximino Martinez", con una edad calculada en mas de 1,300 anos.',
        svgX: 345,
        svgY: 280,
      },
      {
        id: 13,
        nombre: 'Cascadas de Minas Viejas',
        slug: 'cascadas-minas-viejas',
        descripcion: 'Impresionantes caidas gemelas de agua con una altura de 50 metros que precipitan verticalmente sobre pozas de un color turquesa intenso.',
        tokenIcon: 'Layers',
        municipio: 'El Naranjo (Ruta Media)',
        clima: 'Calido humedo',
        logistica: 'Rodeadas de selva densa. Cuenta con infraestructura de puentes colgantes para la exploracion turistica.',
        svgX: 380,
        svgY: 315,
      },
      {
        id: 14,
        nombre: 'Estacion Tablas',
        slug: 'estacion-tablas',
        descripcion: 'Paraje donde afluentes pristinos de agua dulce emergen burbujeantes en un paisaje delineado por el matorral y la vegetacion semidesertica.',
        tokenIcon: 'Sparkles',
        municipio: 'Ciudad del Maiz',
        clima: 'Seco estepario',
        logistica: 'Configura un espacio de reposo familiar, sin grandes infraestructuras invasivas.',
        svgX: 320,
        svgY: 220,
      },
    ],
    pueblos: [
      {
        id: 6,
        nombre: 'Ciudad del Maiz',
        slug: 'ciudad-del-maiz',
        descripcionBreve: 'Encrucijada de civilizaciones en la zona media potosina, donde manantiales milenarios y cuevas con pinturas rupestres narran cuatro siglos de mestizaje.',
        imagenUrl: '/images/ciudad-del-maiz.jpg',
        altitud: 1200,
      },
    ],
  },
];

const pueblosCompletos: PuebloMagico[] = [
  {
    id: 1,
    nombre: 'Aquismon',
    slug: 'aquismon',
    altitud: 100,
    clima: 'Calido montanoso',
    temperaturaMedia: '25 grados centigrados promedio',
    ecosistema: 'Selva mediana y bosque tropical. Vegetacion exuberante con alta biodiversidad, rios caudalosos de aguas turquesa y formaciones karsticas que generan sotanos y cuevas de profundidad extrema.',
    perfilTuristico: 'Ecoturismo de aventura y espeleologia extrema. Destino para rappel en sotanos verticales, navegacion fluvial, senderismo en selva y observacion de aves migratorias en abismos naturales.',
    descripcionBreve: 'Epicentro del ecoturismo extremo en la Huasteca Potosina, hogar de la cascada mas alta de Mexico accesible por rio y de abismos verticales de clase mundial.',
    imagenUrl: '/images/aquismon.jpg',
    regionId: 1,
    region: { id: 1, nombre: 'Huasteca', colorHex: '#166534', descripcion: null },
    atractivos: [
      { id: 1, nombre: 'Cascada de Tamul', descripcion: 'Con 105 metros de altura, es la cascada mas alta de San Luis Potosi. Se forma por la confluencia de los rios Santa Maria y Gallinas sobre el rio Tampaon, cuyas aguas son de un intenso color turquesa. Se accede mediante navegacion en pangas desde las comunidades de La Morena o Tancachitin, con parada intermedia en la Cueva del Agua.', tipo: 'Cascada', estacionalidad: 'Temporada ideal de noviembre a mayo. En verano, las crecientes por lluvias hacen riesgosa la navegacion y pueden impedir el acceso.', acceso: 'Navegacion en panga desde La Morena o Tancachitin. Recorrido fluvial de aproximadamente 45 minutos por el rio Tampaon.', puebloId: 1 },
      { id: 2, nombre: 'Nacimiento de Tambaque', descripcion: 'Conjunto de pozas cristalinas de baja profundidad alimentadas por manantiales subterraneos, rodeadas de vegetacion tropical densa. Ideales para nadar y contemplar la naturaleza.', tipo: 'Manantial', estacionalidad: 'Accesible todo el ano, con mayor afluencia en temporadas calidas.', acceso: 'Carretera pavimentada desde Aquismon, con estacionamiento y senderos senalizados.', puebloId: 1 },
      { id: 3, nombre: 'Sotano de las Golondrinas', descripcion: 'Abismo vertical de 512 metros de profundidad, uno de los sotanos de tiro libre mas profundos del mundo. Habitado por vencejos de pecho blanco y cotorras, que realizan vuelos en espiral al amanecer y atardecer.', tipo: 'Sotano', estacionalidad: 'Observacion optima al amanecer (salida de aves) y atardecer (retorno). Rappel con permisos y equipo especializado.', acceso: 'Terraceria desde Aquismon hasta la comunidad de la Golondrina. Caminata de 30 minutos hasta el borde.', puebloId: 1 },
      { id: 4, nombre: 'Sotano de las Huahuas', descripcion: 'Abismo de 478 metros de profundidad que funciona como santuario natural para pericos verdes. Menos visitado, ofrece una experiencia mas intima con la naturaleza.', tipo: 'Sotano', estacionalidad: 'Todo el ano, con mejor observacion de aves en temporada seca.', acceso: 'Terraceria desde Aquismon con guia local recomendado.', puebloId: 1 },
      { id: 5, nombre: 'Cuevas de Mantetzulel', descripcion: 'Sistema de cuevas accesibles mediante senderismo guiado con interpretes botanicos locales que explican la flora medicinal y la ecologia de la selva circundante.', tipo: 'Cueva', estacionalidad: 'Todo el ano. En temporada de lluvias, algunos senderos pueden ser resbaladizos.', acceso: 'Senderismo con guias botanicos locales desde la comunidad de Mantetzulel.', puebloId: 1 },
      { id: 6, nombre: 'Iglesia de San Miguel Arcangel en Tamapatz', descripcion: 'Templo historico con singular fusion arquitectonica de influencia arabe construida sobre un basamento de origen huasteco.', tipo: 'Monumento historico', estacionalidad: 'Todo el ano.', acceso: 'Carretera desde Aquismon hasta la comunidad de Tamapatz.', puebloId: 1 },
    ],
    culturas: [
      { id: 1, tipo: 'Gastronomia', nombre: 'Zacahuil', descripcion: 'Tamal gigante de masa de maiz con chile ancho y carne de cerdo o guajolote, envuelto en hojas de platano y cocido en horno de lena durante toda la noche.', puebloId: 1 },
      { id: 2, tipo: 'Gastronomia', nombre: 'Bocoles', descripcion: 'Gorditas de maiz gruesas rellenas de frijol, queso o chicharron, fritas y servidas con salsa.', puebloId: 1 },
      { id: 3, tipo: 'Gastronomia', nombre: 'Enchiladas huastecas con cecina', descripcion: 'Tortillas banadas en salsa de chile seco rellenas de queso fresco, acompanadas de cecina curada al sol.', puebloId: 1 },
      { id: 4, tipo: 'Artesania', nombre: 'Textiles de arte Tenek', descripcion: 'Tejidos artesanales elaborados por mujeres de la etnia Tenek: morrales, fajas ceremoniales y quexquemitls con bordados simbolicos.', puebloId: 1 },
    ],
    sostenibilidad: {
      id: 1,
      capacidadCarga: 'La Cascada de Tamul y el Sotano de las Golondrinas tienen capacidad limitada. Se recomienda limitar grupos a 15 personas.',
      riesgosSaturacion: 'En temporada alta, el rio Tampaon puede saturarse de embarcaciones. El exceso de visitantes en el Sotano perturba los patrones de vuelo de las aves.',
      mejoresTemporadas: 'Noviembre a mayo para la Cascada de Tamul. Temporada seca para sotanos. Evitar julio y agosto por lluvias intensas.',
      recomendaciones: 'Contratar guias locales certificados, respetar las zonas de observacion en sotanos, no introducir residuos plasticos en el rio.',
      puebloId: 1,
    },
  },
  {
    id: 2,
    nombre: 'Xilitla',
    slug: 'xilitla',
    altitud: 600,
    clima: 'Semicalido humedo',
    temperaturaMedia: '22 grados centigrados promedio',
    ecosistema: 'Selva humeda de montana con neblina persistente y cafetales organicos de altura.',
    perfilTuristico: 'Turismo cultural, arte surrealista y exploracion botanica.',
    descripcionBreve: 'Enclave surrealista en la selva huasteca, donde las esculturas de concreto de Edward James emergen entre la neblina tropical.',
    imagenUrl: '/images/xilitla.jpg',
    regionId: 1,
    region: { id: 1, nombre: 'Huasteca', colorHex: '#166534', descripcion: null },
    atractivos: [
      { id: 7, nombre: 'Jardin Escultorico de Edward James - Las Pozas', descripcion: '36 estructuras monumentales de concreto inmersas en la selva humeda, creadas por el mecenas britanico Edward James entre 1962 y 1984. Escaleras que no conducen a ninguna parte, columnas con capiteles de flores y puertas que se abren al vacio.', tipo: 'Sitio artistico', estacionalidad: 'Todo el ano. La neblina matutina (noviembre a febrero) otorga una atmosfera dramatica. Controles de capacidad activos.', acceso: 'A 2.5 km del centro de Xilitla por carretera asfaltada.', puebloId: 2 },
      { id: 8, nombre: 'Ex Convento de San Agustin', descripcion: 'Estructura monastica fundada en 1557, la mas antigua del estado. Arquitectura colonial con elementos goticos y renacentistas.', tipo: 'Monumento historico', estacionalidad: 'Todo el ano.', acceso: 'En el centro historico de Xilitla, accesible a pie.', puebloId: 2 },
      { id: 9, nombre: 'Museo Leonora Carrington', descripcion: 'Espacio museografico dedicado a la obra de la artista surrealista britanico-mexicana Leonora Carrington.', tipo: 'Museo', estacionalidad: 'Todo el ano.', acceso: 'En el centro de Xilitla.', puebloId: 2 },
      { id: 10, nombre: 'Castillo de la Salud en Axtla de Terrazas', descripcion: 'Edificacion de Beto Ramon dedicada a la medicina tradicional y herbolaria.', tipo: 'Sitio cultural', estacionalidad: 'Todo el ano.', acceso: 'En Axtla de Terrazas, a 45 minutos de Xilitla.', puebloId: 2 },
    ],
    culturas: [
      { id: 5, tipo: 'Gastronomia', nombre: 'Cafe organico de altura', descripcion: 'Cafe cultivado bajo sombra entre los 600 y 1,000 msnm. Proceso artesanal de secado al sol y tostado en comal con notas achocolatadas y citricas.', puebloId: 2 },
    ],
    sostenibilidad: {
      id: 2,
      capacidadCarga: 'El Jardin Escultorico Las Pozas implementa control de aforo con limite de visitantes simultaneos.',
      riesgosSaturacion: 'Advertencia activa de saturacion turistica, especialmente en fines de semana y periodos vacacionales.',
      mejoresTemporadas: 'Entre semana fuera de temporada vacacional. Noviembre a febrero para la neblina caracteristica.',
      recomendaciones: 'Reservar entrada con anticipacion, visitar temprano por la manana, no tocar las esculturas.',
      puebloId: 2,
    },
  },
  {
    id: 3,
    nombre: 'Real de Catorce',
    slug: 'real-de-catorce',
    altitud: 2700,
    clima: 'Frio a templado extremo',
    temperaturaMedia: '22 grados en verano, inferior a 5 grados en invierno',
    ecosistema: 'Semidesierto y alta montana. Paisaje arido con matorral xerofitico, cactaceas columnares y pastizales de alta montana.',
    perfilTuristico: 'Mistico, patrimonio historico minero y peregrinacion.',
    descripcionBreve: 'Pueblo fantasma minero suspendido a 2,700 metros de altitud, accesible unicamente a traves de un tunel del siglo XIX.',
    imagenUrl: '/images/real-de-catorce.jpg',
    regionId: 2,
    region: { id: 2, nombre: 'Altiplano', colorHex: '#B45309', descripcion: null },
    atractivos: [
      { id: 11, nombre: 'Tunel de Ogarrio', descripcion: 'Unico acceso terrestre, un tunel de 2,300 metros perforado en la roca en 1897. Carretera de un solo carril con semaforos.', tipo: 'Monumento historico', estacionalidad: 'Todo el ano. Posibles esperas de 30 minutos.', acceso: 'Vehiculo propio o transporte Willys desde Estacion Catorce.', puebloId: 3 },
      { id: 12, nombre: 'Ruinas de mamposteria - Pueblo Fantasma', descripcion: 'Edificaciones abandonadas del siglo XIX: Palenque de Gallos, Plaza de Toros, Antigua Casa de la Moneda (1815).', tipo: 'Zona arqueologica', estacionalidad: 'Todo el ano.', acceso: 'Recorrido a pie por el pueblo.', puebloId: 3 },
      { id: 13, nombre: 'Parroquia de la Purisima Concepcion', descripcion: 'Templo que resguarda la imagen de San Francisco de Asis, centro de peregrinacion cada 4 de octubre.', tipo: 'Templo', estacionalidad: 'Todo el ano. Mayor afluencia en octubre.', acceso: 'Centro del pueblo, a pie.', puebloId: 3 },
      { id: 14, nombre: 'Area Natural Protegida de Wirikuta y Cerro del Quemado', descripcion: 'Territorio sagrado Wixarika de 140,000 hectareas. Cerro del Quemado: sitio ceremonial para la comunion ritual con el hikuri (peyote).', tipo: 'Area natural protegida', estacionalidad: 'Todo el ano. Respetar periodos de peregrinacion Wixarika (febrero a marzo).', acceso: 'Vehiculos todoterreno Willys.', puebloId: 3 },
      { id: 15, nombre: 'Recorridos en Willys y Ex Hacienda Laguna Seca', descripcion: 'Excursiones en vehiculos Willys hacia Estacion Catorce y la Ex Hacienda Laguna Seca con destilacion de mezcal tradicional.', tipo: 'Recorrido', estacionalidad: 'Todo el ano.', acceso: 'Contratacion de Willys con conductor local.', puebloId: 3 },
    ],
    culturas: [],
    sostenibilidad: {
      id: 3,
      capacidadCarga: 'El Tunel de Ogarrio limita naturalmente el flujo vehicular. Las calles del siglo XIX no soportan trafico masivo.',
      riesgosSaturacion: 'La peregrinacion en octubre genera picos extremos. El turismo no regulado en Wirikuta amenaza sitios ceremoniales.',
      mejoresTemporadas: 'Primavera y otono para clima moderado. Evitar invierno por temperaturas bajo cero.',
      recomendaciones: 'Respetar sitios sagrados Wixarika, no recolectar peyote (ilegal), llevar ropa abrigada, contratar guias locales.',
      puebloId: 3,
    },
  },
  {
    id: 4,
    nombre: 'Santa Maria del Rio',
    slug: 'santa-maria-del-rio',
    altitud: 1700,
    clima: 'Semidesertico arbustivo',
    temperaturaMedia: '18 grados centigrados promedio',
    ecosistema: 'Matorral semidesertico arbustivo con vegetacion xerofitica.',
    perfilTuristico: 'Turismo cultural textil, termalismo y patrimonio hacendario.',
    descripcionBreve: 'Capital mundial del rebozo mexicano, donde la tradicion textil de cuatro siglos se preserva en telares de cintura.',
    imagenUrl: '/images/santa-maria-del-rio.jpg',
    regionId: 3,
    region: { id: 3, nombre: 'Centro', colorHex: '#9A3412', descripcion: null },
    atractivos: [
      { id: 16, nombre: 'Cauce del Rio Santa Maria', descripcion: 'Rio que atraviesa la localidad y da nombre al municipio.', tipo: 'Rio', estacionalidad: 'Mayor caudal en temporada de lluvias (julio a octubre).', acceso: 'Accesible desde multiples puntos del pueblo.', puebloId: 4 },
      { id: 17, nombre: 'Balneario de Aguas Termales de Lourdes', descripcion: 'Manantiales de aguas termales de composicion sulfurosa con propiedades terapeuticas. Temperatura de 36 a 40 grados.', tipo: 'Balneario termal', estacionalidad: 'Todo el ano.', acceso: 'A pocos kilometros del centro por carretera pavimentada.', puebloId: 4 },
      { id: 18, nombre: 'Cascada El Salto', descripcion: 'Caida de agua estacional de 30 a 40 metros. Visible unicamente en temporada de lluvias.', tipo: 'Cascada', estacionalidad: 'Julio a octubre exclusivamente. Resto del ano seca.', acceso: 'Camino rural. Se recomienda vehiculo alto.', puebloId: 4 },
      { id: 19, nombre: 'Parque Nacional El Gogorron', descripcion: 'Area natural protegida con ecosistemas de matorral xerofilo y pastizal.', tipo: 'Parque nacional', estacionalidad: 'Todo el ano.', acceso: 'Carretera federal en la periferia.', puebloId: 4 },
      { id: 20, nombre: 'Parroquia de Nuestra Senora de la Asuncion', descripcion: 'Templo colonial principal. La plaza adyacente alberga la Torre del Reloj Bicentenario.', tipo: 'Templo', estacionalidad: 'Todo el ano.', acceso: 'Centro historico.', puebloId: 4 },
      { id: 21, nombre: 'Haciendas historicas', descripcion: 'Haciendas coloniales: Lourdes, Villa Quemada, Badillo y Labor del Rio.', tipo: 'Patrimonio historico', estacionalidad: 'Todo el ano. Algunas son propiedad privada.', acceso: 'Caminos rurales en los alrededores.', puebloId: 4 },
    ],
    culturas: [
      { id: 6, tipo: 'Artesania', nombre: 'Escuela-Museo Casa del Rebozo', descripcion: 'Institucion dedicada a la preservacion del rebozo en telar de cintura con tecnica del ikat.', puebloId: 4 },
      { id: 7, tipo: 'Gastronomia', nombre: 'Asado de boda', descripcion: 'Carne de cerdo en salsa de chiles secos con especias, chocolate y frutas. Platillo ceremonial.', puebloId: 4 },
      { id: 8, tipo: 'Gastronomia', nombre: 'Gorditas y carnitas', descripcion: 'Gorditas de maiz rellenas con carnitas de cerdo fritas en manteca, con nopalitos.', puebloId: 4 },
      { id: 9, tipo: 'Gastronomia', nombre: 'Queso de tuna y campechanas', descripcion: 'Dulce artesanal de tuna cocido hasta pasta solida. Campechanas: hojaldre dulce crujiente.', puebloId: 4 },
    ],
    sostenibilidad: {
      id: 4,
      capacidadCarga: 'La Cascada El Salto tiene acceso limitado en temporada de lluvias. Las aguas termales manejan aforo controlado.',
      riesgosSaturacion: 'Riesgo moderado. La actividad textil se ve amenazada por falta de relevo generacional.',
      mejoresTemporadas: 'Julio a octubre para la cascada. Todo el ano para aguas termales y Casa del Rebozo.',
      recomendaciones: 'Adquirir rebozos directamente de artesanas locales.',
      puebloId: 4,
    },
  },
  {
    id: 5,
    nombre: 'Tierra Nueva',
    slug: 'tierra-nueva',
    altitud: 1800,
    clima: 'Montana y canadas profundas',
    temperaturaMedia: '17 grados centigrados promedio',
    ecosistema: 'Paisaje de montana con canadas profundas, bosques de encino y matorral.',
    perfilTuristico: 'Turismo rural, pesca deportiva y patrimonio historico-religioso.',
    descripcionBreve: 'Pueblo serrano de canadas profundas y laja roja, donde una iglesia sumergida emerge cuando desciende la presa.',
    imagenUrl: '/images/tierra-nueva.jpg',
    regionId: 3,
    region: { id: 3, nombre: 'Centro', colorHex: '#9A3412', descripcion: null },
    atractivos: [
      { id: 22, nombre: 'Presa La Muneca', descripcion: 'Embalse sobre el Rio Jofre con pesca deportiva. En estiaje emergen ruinas sumergidas de la comunidad de Vigas.', tipo: 'Presa', estacionalidad: 'Pesca todo el ano. Ruinas visibles febrero a mayo.', acceso: 'Carretera desde Tierra Nueva, 20 minutos.', puebloId: 5 },
      { id: 23, nombre: 'Cerro La Mesa - Salsipuedes', descripcion: 'Montana con senderos en canadas profundas. Carga historica de la Guerra Cristera.', tipo: 'Senderismo', estacionalidad: 'Otono e invierno. Evitar lluvias por deslizamientos.', acceso: 'Senderos con guia local recomendado.', puebloId: 5 },
      { id: 24, nombre: 'Parroquia de San Nicolas Tolentino', descripcion: 'Notable por sus tres torres campanario asimetricas, una rareza arquitectonica en la region.', tipo: 'Templo', estacionalidad: 'Todo el ano.', acceso: 'Centro de Tierra Nueva.', puebloId: 5 },
    ],
    culturas: [
      { id: 10, tipo: 'Festividad', nombre: 'Fiestas patronales', descripcion: 'Del 1 al 10 de septiembre con procesiones, danzas, musica de banda y pirotecnia.', puebloId: 5 },
      { id: 11, tipo: 'Gastronomia', nombre: 'Barbacoa tradicional', descripcion: 'Carne cocida en horno de tierra con pencas de maguey toda la noche.', puebloId: 5 },
      { id: 12, tipo: 'Gastronomia', nombre: 'Gorditas de garbanzo', descripcion: 'Gorditas rellenas de garbanzo guisado con chiles secos, especialidad unica local.', puebloId: 5 },
      { id: 13, tipo: 'Gastronomia', nombre: 'Melcocha de tuna', descripcion: 'Dulce elaborado estirando jarabe de tuna cocido hasta obtener textura fibrosa y cristalina.', puebloId: 5 },
      { id: 14, tipo: 'Artesania', nombre: 'Laja roja y sombreros de palma', descripcion: 'La laja roja "sangre de pichon" es piedra ornamental local. Sombreros de palma artesanales de exportacion.', puebloId: 5 },
    ],
    sostenibilidad: {
      id: 5,
      capacidadCarga: 'Presa La Muneca tiene capacidad amplia. Senderos del Cerro La Mesa requieren condicion fisica.',
      riesgosSaturacion: 'Riesgo bajo. Turismo incipiente con infraestructura limitada.',
      mejoresTemporadas: 'Febrero a mayo para ruinas sumergidas. Septiembre para fiestas. Otono-invierno para senderismo.',
      recomendaciones: 'Equipo adecuado para senderismo, respetar zonas de pesca reguladas, apoyar economia local.',
      puebloId: 5,
    },
  },
  {
    id: 6,
    nombre: 'Ciudad del Maiz',
    slug: 'ciudad-del-maiz',
    altitud: 1200,
    clima: 'Transicion serrana a arida',
    temperaturaMedia: '20 grados centigrados promedio',
    ecosistema: 'Zona de transicion entre la sierra madre y las planicies aridas. Vegetacion mixta con manantiales termales.',
    perfilTuristico: 'Turismo historico-cultural, termalismo natural y espeleologia arqueologica.',
    descripcionBreve: 'Encrucijada de civilizaciones en la zona media, con manantiales milenarios y cuevas con pinturas rupestres.',
    imagenUrl: '/images/ciudad-del-maiz.jpg',
    regionId: 4,
    region: { id: 4, nombre: 'Media', colorHex: '#A16207', descripcion: null },
    atractivos: [
      { id: 25, nombre: 'Parroquia de la Purisima Concepcion', descripcion: 'Templo del siglo XVIII neoclasico con restos del Gral. Miguel Barragan y reloj parisino.', tipo: 'Templo', estacionalidad: 'Todo el ano.', acceso: 'Centro historico.', puebloId: 6 },
      { id: 26, nombre: 'Jardin Hidalgo con kiosco afrancesado', descripcion: 'Plaza con kiosco de hierro fundido de estilo afrancesado del Porfiriato.', tipo: 'Plaza', estacionalidad: 'Todo el ano.', acceso: 'Centro de Ciudad del Maiz.', puebloId: 6 },
      { id: 27, nombre: 'Murales en El Tepeyac', descripcion: '"Ritual de una alegoria" (1955). Arte publico que refleja la identidad cultural y religiosa.', tipo: 'Arte publico', estacionalidad: 'Todo el ano.', acceso: 'Localidad de El Tepeyac.', puebloId: 6 },
      { id: 28, nombre: 'Manantiales Los Peroles', descripcion: 'Oasis cristalino de aguas termales con el sabino "Maximino Martinez" de mas de 1,300 anos.', tipo: 'Manantial termal', estacionalidad: 'Todo el ano. Mejor en temporada seca.', acceso: 'Camino rural, acceso libre.', puebloId: 6 },
      { id: 29, nombre: 'Estacion Tablas', descripcion: 'Paraje con afluentes de agua dulce en entorno de transicion ecologica.', tipo: 'Paraje natural', estacionalidad: 'Todo el ano.', acceso: 'Camino rural desde Ciudad del Maiz.', puebloId: 6 },
      { id: 30, nombre: 'Cueva Vetada de San Bartolo', descripcion: 'Cueva con pinturas rupestres y herramientas de obsidiana chichimecas.', tipo: 'Cueva arqueologica', estacionalidad: 'Todo el ano. Acceso restringido.', acceso: 'Con guia local desde San Bartolo. Se requiere permiso.', puebloId: 6 },
      { id: 31, nombre: 'Cueva del Oso', descripcion: 'Formacion geologica con evidencia de ocupacion prehistorica.', tipo: 'Cueva', estacionalidad: 'Todo el ano.', acceso: 'Con guia local.', puebloId: 6 },
      { id: 32, nombre: 'Cascadas de Minas Viejas', descripcion: 'Caida de agua de 35 metros en anfiteatro natural, en el municipio vecino de El Naranjo.', tipo: 'Cascada', estacionalidad: 'Mayor espectacularidad julio a octubre.', acceso: 'Carretera Ciudad del Maiz - El Naranjo.', puebloId: 6 },
    ],
    culturas: [
      { id: 15, tipo: 'Gastronomia', nombre: 'Guiso borracho', descripcion: 'Platillo a base de pulque, carnes y vegetales en guiso lento con sabores fermentados.', puebloId: 6 },
      { id: 16, tipo: 'Festividad', nombre: 'Festividad del Senor del Salitre', descripcion: 'Celebracion principal entre julio y agosto con procesiones, danzas Xi\'iuy y feria popular.', puebloId: 6 },
    ],
    sostenibilidad: {
      id: 6,
      capacidadCarga: 'Los Peroles carecen de infraestructura formal, limitando naturalmente el aforo. Cuevas con acceso restringido.',
      riesgosSaturacion: 'Riesgo bajo. Principal riesgo: deterioro de pinturas rupestres por visitantes no supervisados.',
      mejoresTemporadas: 'Todo el ano para el pueblo y Los Peroles. Julio-agosto para la festividad. Lluvias para las cascadas.',
      recomendaciones: 'No tocar pinturas rupestres, respetar entorno de Los Peroles, contratar guias locales para cuevas.',
      puebloId: 6,
    },
  },
];

export default regionesData;

export function obtenerPuebloPorSlug(slug: string): PuebloMagico | undefined {
  return pueblosCompletos.find((p) => p.slug === slug);
}

export function obtenerDatosComparativos(): PuebloComparativo[] {
  return pueblosCompletos.map((p) => ({
    id: p.id,
    nombre: p.nombre,
    slug: p.slug,
    altitud: p.altitud,
    clima: p.clima,
    temperaturaMedia: p.temperaturaMedia,
    ecosistema: p.ecosistema,
    perfilTuristico: p.perfilTuristico,
    region: {
      nombre: p.region.nombre,
      colorHex: p.region.colorHex,
    },
    _count: {
      atractivos: p.atractivos.length,
      culturas: p.culturas.length,
    },
  }));
}

export function buscarPueblosMagicos(termino: string): PuebloMagico[] {
  const t = termino.toLowerCase();
  return pueblosCompletos.filter(
    (p) =>
      p.nombre.toLowerCase().includes(t) ||
      p.region.nombre.toLowerCase().includes(t) ||
      (p.descripcionBreve && p.descripcionBreve.toLowerCase().includes(t))
  );
}
